spring:
  application:
    name: notification-events
  autoconfigure:
    exclude:
      - org.springframework.boot.amqp.autoconfigure.RabbitAutoConfiguration
      - org.springframework.boot.data.jpa.autoconfigure.DataJpaRepositoriesAutoConfiguration
      - org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
